const data = {
  patientList: {
    name: '胡定明', //姓名
    sex: '男', //性别
    age: '65', //年龄
    endemicName: '心内科', //科室
    bedNo: '123', //床号
    inpNo: 'Z23456', //住院号
  }, //病人信息
  beginDate: '2017-06-28', //开始时间,按今天倒推7天
  dayList: ['1', '2', '3', '4', '5', '6', '7'], //住院天数 共七条，没有的那天数据返回''
  dayOps: ['1', '2', '3', '4', '5', '6', '7'], //产后/术后天数 共七条，没有的那天数据返回''
  breathingList: [
    '60',
    '70',
    '65',
    '66',
    '56',
    '60',
    '70',
    '60',
    '70',
    '65',
    '66',
    '56',
    '60',
    '70',
    '60',
    '70',
    '65',
    '66',
    '56',
    '60',
    '70',
    '60',
    '70',
    '65',
    '66',
    '56',
    '60',
    '70',
    '60',
    '70',
    '65',
    '66',
    '56',
    '60',
    '70',
    '60',
    '70',
    '65',
    '66',
    '56',
    '60',
    '70',
  ], //呼吸 42条数据 某个时间点空值返回''
  xyList: ['60', '70', '65', '66', '56', '60', '70', '60', '70', '65', '66', '56', '60', '70'], //血压 14条，当天空值返回''
  dayMap: {
    "{name:'入量',units:'ml'}": ['', '', '', '', '', '44', ''], //7条数据对应7天的入量
    "{name:'出量',units:'ml'}": ['', '', '', '', '', '44', ''], //以此类推...
    "{name:'小便',units:'ml'}": ['', '', '', '', '', '44', ''],
    "{name:'大便',units:'次/日'}": ['', '', '', '', '', '44', ''],
    "{name:'体重',units:'kg'}": ['', '', '', '', '', '47.5', ''],
    "{name:'血氧饱和度',units:''}": ['', '', '', '', '', '47.5', ''],
    "{name:'过敏史',units:''}": ['', '', '', '', '', '47.5', ''],
  }, //每日录入信息
  pointTime: {
    // 脉搏
    mb: [
      {
        dataTime: '2017-06-28 22:00:00',
        date: '2017-06-28',
        hour: 22,
        mbValue: '',
        phValue: '',
        type: '',
        value: '88',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 06:00:00',
        date: '2017-06-29',
        hour: 6,
        mbValue: '',
        phValue: '',
        type: '',
        value: '160',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 14:00:00',
        date: '2017-06-29',
        hour: 14,
        mbValue: '',
        phValue: '',
        type: '',
        value: '100',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 18:00:00',
        date: '2017-06-29',
        hour: 18,
        mbValue: '',
        phValue: '',
        type: '',
        value: '120',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 22:00:00',
        date: '2017-06-29',
        hour: 22,
        mbValue: '',
        phValue: '',
        type: '',
        value: '150',
        xlValue: '',
      },
    ],
    // 温度
    wd: [
      {
        dataTime: '2017-06-29 22:00:00',
        date: '2017-06-28',
        hour: 22,
        mbValue: '',
        phValue: '36.5',
        type: 'ew', // 耳温
        value: '37.2',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 06:00:00',
        date: '2017-06-29',
        hour: 6,
        mbValue: '',
        phValue: '',
        type: 'ew', // 耳温
        value: '37',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 14:00:00',
        date: '2017-06-29',
        hour: 14,
        mbValue: '',
        phValue: '',
        type: 'ew', // 耳温
        value: '37.5',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 18:00:00',
        date: '2017-06-29',
        hour: 18,
        mbValue: '',
        phValue: '',
        type: 'ew', // 耳温
        value: '37.4',
        xlValue: '',
      },
      {
        dataTime: '2017-06-29 22:00:00',
        date: '2017-06-29',
        hour: 22,
        mbValue: '',
        phValue: '',
        type: 'ew', // 耳温
        value: '36.8',
        xlValue: '',
      },
    ],
  }, // 时间段录入信息
};
export const tableData = {
  code: 200,
  data: [
    {
      age: 86,
      archiveId: '627078904540172288',
      bed: '健康管理中心-三楼-东边套01/04房-02床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '20220927095050',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '陈炳柳',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '1',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 83,
      archiveId: '524269951712890880',
      bed: '健康管理中心-三楼-中间套05/08房-05床不带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202112191103',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '喻水仙',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 87,
      archiveId: '546966126291193856',
      bed: '健康管理中心-三楼-中间套05/08房-06床不带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202202180809',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '吕仁珍',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 83,
      archiveId: '536508614047830016',
      bed: '健康管理中心-三楼-中间套05/08房-07床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202201201134',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '柴锦敏',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 87,
      archiveId: '524884296775897088',
      bed: '健康管理中心-三楼-中间套05/08房-08床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202202180811',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '韩爱金',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 88,
      archiveId: '627083147162554368',
      bed: '健康管理中心-三楼-中间套09/12房-09床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '20220927100552',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '巴银花',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 92,
      archiveId: '524874242907574272',
      bed: '健康管理中心-三楼-中间套09/12房-10床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202112191108',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '傅水林',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 78,
      archiveId: '523882055675809792',
      bed: '健康管理中心-三楼-中间套09/12房-11床不带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202112191046',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '何玉妹',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 78,
      archiveId: '524874740985368576',
      bed: '健康管理中心-三楼-中间套09/12房-12床不带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202202191522',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '王爱娟',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 94,
      archiveId: '523883940260483072',
      bed: '健康管理中心-四楼-东边套01/04房-02床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '20221024083545',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '倪仁娟',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 94,
      archiveId: '523876436860342272',
      bed: '健康管理中心-四楼-中间套05/08房-06床不带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202112191035',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '李祥法',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '1',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 88,
      archiveId: '627084598643396608',
      bed: '健康管理中心-四楼-中间套05/08房-07床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '20220927101551',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '屠荣禄',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '1',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 85,
      archiveId: '523880682603286528',
      bed: '健康管理中心-四楼-中间套05/08房-08床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202112191036',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '赵关木',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '1',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 90,
      archiveId: '523887809241681920',
      bed: '健康管理中心-四楼-中间套09/12房-10床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202112191054',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '丁阿兰',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 89,
      archiveId: '627086929195831296',
      bed: '健康管理中心-四楼-中间套09/12房-11床不带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '20220927102057',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '张飞吾',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 87,
      archiveId: '552806553007296512',
      bed: '健康管理中心-四楼-中间套09/12房-12床不带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202203061059',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '沈丽娟',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
    {
      age: 89,
      archiveId: '523876006612832256',
      bed: '健康管理中心-四楼-西边套13/16房-16床带阳台',
      bloodOxygen: null,
      breathing: null,
      businessNo: '202112191033',
      createTime: '',
      creatorId: null,
      defecate: null,
      defecatePattern: '',
      highBloodPressure: null,
      id: null,
      intake: '',
      lowBloodPressure: null,
      name: '李官囡',
      nurseSign: '',
      output: '',
      pulse: null,
      recordTime: '',
      sex: '2',
      temperature: '',
      timePoint: '',
      urine: '',
      weight: '',
    },
  ],
  msg: '提交成功',
};

export const chartData = {
  code: 200,
  data: {
    beginDate: '2022-11-23',
    breathingList: [
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '18',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '18',
      '',
      '',
    ],
    dayList: ['596', '597', '598', '599', '600', '601', '602'],
    dayMap: {
      "{name:'入量',units:'ml'}": ['', '', '', '', '', '', ''],
      "{name:'血氧饱和度',units:''}": ['', '', '', '', '', '', ''],
      "{name:'大便',units:'次/日'}": ['1', '1', '1', '1', '1', '1', '1'],
      "{name:'出量',units:'ml'}": ['', '', '', '', '', '', ''],
      "{name:'小便',units:'ml'}": ['', '', '', '', '', '', ''],
      "{name:'体重',units:'kg'}": ['', '', '', '', '', '', ''],
    },
    dayOps: ['', '', '', '', '', '', ''],
    patientInfoList: {
      age: '83',
      bedName: '05床不带阳台',
      businessNo: '202112191103',
      endemicName: '',
      name: '喻水仙',
      sex: '女',
    },
    pointTime: {
      mb: [
        {
          dataTime: '2022-11-23 14:00',
          date: '2022-11-23',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '105',
          xlValue: '',
        },
        {
          dataTime: '2022-11-24 14:00',
          date: '2022-11-24',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '97',
          xlValue: '',
        },
        {
          dataTime: '2022-11-25 14:00',
          date: '2022-11-25',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '90',
          xlValue: '',
        },
        {
          dataTime: '2022-11-26 14:00',
          date: '2022-11-26',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '106',
          xlValue: '',
        },
        {
          dataTime: '2022-11-27 14:00',
          date: '2022-11-27',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '88',
          xlValue: '',
        },
        {
          dataTime: '2022-11-28 14:00',
          date: '2022-11-28',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '89',
          xlValue: '',
        },
        {
          dataTime: '2022-11-29 14:00',
          date: '2022-11-29',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '91',
          xlValue: '',
        },
      ],
      wd: [
        {
          dataTime: '2022-11-23 14:00',
          date: '2022-11-23',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.5',
          xlValue: '',
        },
        {
          dataTime: '2022-11-24 14:00',
          date: '2022-11-24',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.3',
          xlValue: '',
        },
        {
          dataTime: '2022-11-25 14:00',
          date: '2022-11-25',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.4',
          xlValue: '',
        },
        {
          dataTime: '2022-11-26 14:00',
          date: '2022-11-26',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.7',
          xlValue: '',
        },
        {
          dataTime: '2022-11-27 14:00',
          date: '2022-11-27',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.3',
          xlValue: '',
        },
        {
          dataTime: '2022-11-28 14:00',
          date: '2022-11-28',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.3',
          xlValue: '',
        },
        {
          dataTime: '2022-11-29 14:00',
          date: '2022-11-29',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.0',
          xlValue: '',
        },
      ],
    },
    xyList: [
      '',
      '115/77',
      '',
      '127/72',
      '',
      '140/68',
      '',
      '128/69',
      '',
      '132/78',
      '',
      '125/70',
      '',
      '137/72',
    ],
  },
  msg: '提交成功',
};
export const chartData2 = {
  code: 200,
  data: {
    beginDate: '2022-11-23',
    breathingList: [
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '19',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '20',
      '',
      '',
      '',
      '',
      '',
      '18',
      '',
      '',
    ],
    dayList: ['280', '281', '282', '283', '284', '285', '286'],
    dayMap: {
      "{name:'入量',units:'ml'}": ['', '', '', '', '', '', ''],
      "{name:'血氧饱和度',units:''}": ['', '', '', '', '', '', ''],
      "{name:'大便',units:'次/日'}": ['1', '1', '1', '1', '1', '1', '1'],
      "{name:'出量',units:'ml'}": ['', '', '', '', '', '', ''],
      "{name:'小便',units:'ml'}": ['', '', '', '', '', '', ''],
      "{name:'体重',units:'kg'}": ['', '', '', '', '', '', ''],
    },
    dayOps: ['', '', '', '', '', '', ''],
    patientInfoList: {
      age: '87',
      bedName: '06床不带阳台',
      businessNo: '202202180809',
      endemicName: '',
      name: '吕仁珍',
      sex: '女',
    },
    pointTime: {
      mb: [
        {
          dataTime: '2022-11-23 14:00',
          date: '2022-11-23',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '83',
          xlValue: '',
        },
        {
          dataTime: '2022-11-24 14:00',
          date: '2022-11-24',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '80',
          xlValue: '',
        },
        {
          dataTime: '2022-11-25 14:00',
          date: '2022-11-25',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '82',
          xlValue: '',
        },
        {
          dataTime: '2022-11-26 14:00',
          date: '2022-11-26',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '87',
          xlValue: '',
        },
        {
          dataTime: '2022-11-27 14:00',
          date: '2022-11-27',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '79',
          xlValue: '',
        },
        {
          dataTime: '2022-11-28 14:00',
          date: '2022-11-28',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '84',
          xlValue: '',
        },
        {
          dataTime: '2022-11-29 14:00',
          date: '2022-11-29',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: '',
          value: '77',
          xlValue: '',
        },
      ],
      wd: [
        {
          dataTime: '2022-11-23 14:00',
          date: '2022-11-23',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.5',
          xlValue: '',
        },
        {
          dataTime: '2022-11-24 14:00',
          date: '2022-11-24',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.3',
          xlValue: '',
        },
        {
          dataTime: '2022-11-25 14:00',
          date: '2022-11-25',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.5',
          xlValue: '',
        },
        {
          dataTime: '2022-11-26 14:00',
          date: '2022-11-26',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.6',
          xlValue: '',
        },
        {
          dataTime: '2022-11-27 14:00',
          date: '2022-11-27',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.4',
          xlValue: '',
        },
        {
          dataTime: '2022-11-28 14:00',
          date: '2022-11-28',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.7',
          xlValue: '',
        },
        {
          dataTime: '2022-11-29 14:00',
          date: '2022-11-29',
          hour: 14,
          mbValue: '',
          phValue: '',
          type: 'ew',
          value: '36.3',
          xlValue: '',
        },
      ],
    },
    xyList: [
      '',
      '111/68',
      '',
      '119/71',
      '',
      '103/65',
      '',
      '116/66',
      '',
      '106/63',
      '',
      '115/72',
      '',
      '102/58',
    ],
  },
  msg: '提交成功',
};
